
steps:
  - id: Initiate gcloud
    name: gcr.io/cloud-builders/gcloud
    entrypoint: sh
    args:
      - '-c'
      - |

        echo
        echo "**********************************************"
        echo "* Set backend project Id *"
        echo "**********************************************"
        echo

        gcloud config set project ${_PROJECT_ID}

        echo
        echo "**********************************************"
        echo "* Set compute region *"
        echo "**********************************************"
        echo

        gcloud config set compute/region ${_PROJECT_REGION}
          
  - id: Build and deploy firebase
    name: node:10.22-alpine
    entrypoint: sh
    args:
      - '-c'
      - |

        echo
        echo "**********************************************"
        echo "* Install firebase *"
        echo "**********************************************"
        echo

        npm install -g firebase-tools
        npm install --save firebase-functions@latest

        echo
        echo "**********************************************"
        echo "* Install modules *"
        echo "**********************************************"
        echo

        cd ./functions
        npm install

        echo
        echo "**********************************************"
        echo "* Deploy functions *"
        echo "**********************************************"
        echo

        firebase deploy --only functions --project=${_PROJECT_ID} --token=${_FIREBASE_TOKEN}

        echo
        echo "**********************************************"
        echo "* Deploy rules *"
        echo "**********************************************"
        echo

        firebase deploy --only firestore:rules --project=${_PROJECT_ID} --token=${_FIREBASE_TOKEN}

        echo
        echo "**************************************"
        echo "* Deploy Storage Rules *"
        echo "**************************************"
        echo
        firebase deploy --only storage:rules --project=${_PROJECT_ID} --token=${_FIREBASE_TOKEN}

        