
steps:
  - id: Initiate gcloud
    name: gcr.io/cloud-builders/gcloud
    entrypoint: sh
    args:
      - '-c'
      - |

        echo
        echo "**********************************************"
        echo "* Set backend project Id *"
        echo "**********************************************"
        echo

        gcloud config set project ${_PROJECT_ID}

        echo
        echo "**********************************************"
        echo "* Set compute region *"
        echo "**********************************************"
        echo

        gcloud config set compute/region ${_PROJECT_REGION}
          
  - id: Build and deploy firebase
    name: node:10.22-alpine
    entrypoint: sh
    args:
      - '-c'
      - |

        echo
        echo "**********************************************"
        echo "* Build functions *"
        echo "**********************************************"
        echo

          cd ./functions
          npm install
          npm run lint
          npm run build
          
  - id: "Deploy functions"
    name: "gcr.io/$PROJECT_ID/firebase"
    args: [
      "deploy",
      "--only=functions",
      "--project=${_PROJECT_ID}"
    ]

  - id: "Deploy firestore rules"
    name: "gcr.io/$PROJECT_ID/firebase"
    args: [
      "deploy", 
      "--only=firestore:rules", 
      "--project=${_PROJECT_ID}"
    ]