version: '3.3'

services:
  dok:
    container_name: dok
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: .
        target: /app/
    tty: true
    network_mode: "host"
    environment: 
      NODE_ENV: local