name: doctors_of_kenya
description: Doctors of Kenya.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.2+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Spinner
  flutter_spinkit: ^4.1.2
  # Fonts
  google_fonts: ^1.1.1
  # Imaging
  cached_network_image: ^2.2.0+1
  # Firebase
  # ***---REQUIREMENT---***
  firebase_core: ^0.7.0
  firebase_analytics: ^7.0.1
  firebase_crashlytics: ^0.4.0+1
  firebase_auth: ^0.20.1
  cloud_firestore: ^0.16.0+1
  firebase_storage: ^7.0.0
  firebase_performance: ^0.5.0+1
  # Provider
  provider: ^4.3.3
  # stepper forms
  # im_stepper: ^0.1.2+8

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
