name: Build and Release APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '1.8'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'

    # Clean Slate
    - run: flutter clean

    # Enable Web (May be redundant)
    - run: flutter config --enable-web

    # Get Packages
    - run: flutter pub get

    # Build
    - run: flutter build apk --shrink --target-platform android-arm
    - run: flutter build web

    - name: Push APK to Releases
      uses: ncipollo/release-action@v1
      with:
        commit: main
        artifacts: "build/app/outputs/flutter-apk/*.apk"
        token: ${{ secrets.TOKEN }}
        tag: v1.1.${{ github.run_number }}

    # - name: Upload APK on Build Artifacts
    #   uses: actions/upload-artifact@v1
    #   with:
    #     name: app
    #     path: build/app/outputs/apk/release/app-release.apk
        
    - name: Upload APK to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
      with:
        appId: ${{ secrets.FIREBASE_APP_ID }}
        token: ${{ secrets.FIREBASE_TOKEN }}
        groups: admin
        file: build/app/outputs/apk/release/app-release.apk

    - name: Deploy to Firebase Hosting
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DOCTORS_OF_KENYA }}'
        channelId: live
        projectId: '${{ secrets.PROJECT_ID }}'
      env:
        FIREBASE_CLI_PREVIEWS: hostingchannels